domain: bkrumnow.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://bkrumnow.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl:     # place folder name if the site is served in a subfolder

remote_theme: pages-themes/midnight@v0.2.0
#theme: jekyll-theme-midnight
#remote_theme: peterdesmet/petridish@2.0
plugins:
- jekyll-remote-theme

title: Benjamin Krumnow

exclude:
  - doc
